### ISSUE TITLE
FlatUIColors

### ISSUE THREAD

**Issue by Sakoutecher** [Aelweak/liens-utiles#3]
URL : https://flatuicolors.com/
Section ciblée : Webdesign > Palettes couleurs
Description/Commentaire :
Bonjour à toi, j'utilise souvent cette outils avec tout ces liens que tu met à disposition et j'aimerais donc y contribuer :).
Je propose donc d'ajouter ce site, qui répertorie un ensemble de palette de couleur. Je te laisse aller dessus et voir par toi même.

Merci :)

**Comment by Sakoutecher** [comment]
Suite à cette issue j'ai pris la liberté de te proposer une PR :) #4

**Comment by Aelweak** [comment]
Salut @Sakoutecher 👋,

Merci pour la proposition de lien 👍.

Je trouve le site un peu "léger" ("seulement" 14 palettes et assez "spécifiques" qui plus est) en comparaison des autres déjà présents dans la liste.
_(Mon but n'étant pas forcément de répertorier le plus de sites possibles)_

En revanche, je garde le lien accessible via _"120K UI Icons"_ (https://www.streamlinehq.com/) dans un coin et l'ajouterai certainement à la prochaine MAJ.

PS : Je dois ajouter encore certaines choses/fonctionnalités prochainement et essaierai de trouver un moyen de citer correctement les contributions.

**Comment by Sakoutecher** [comment]
Ca marche pas de soucis :)
