### ISSUE TITLE
Add_pigment.shapefactory.co/

### ISSUE THREAD

**Issue by Vavart** [Aelweak/liens-utiles#6]
URL : https://pigment.shapefactory.co/
Section ciblée : Webdesign
Description/Commentaire : Site utile pour tester des couleurs et appliquer un joli filtre sur les images

**Comment by Aelweak** [comment]
Merci @Vavart 🙏,
Il sera ajouté à la prochaine MAJ dans _Webdesign > Palettes couleurs_
Pour le reste de ses fonctionnalités, petite préférence pour : https://photomosh.com/ (qu'il faut que j'ajoute également) 😊.
