### ISSUE TITLE
Verifier l'état des lien avec une requete http

### ISSUE THREAD

**Issue by gloirekiba** [Aelweak/liens-utiles#7]
Bonjour, j'avais une proposition de fonctionnalité à faire.
L’or de l'affichage d'un lien, pourquoi ne pas faire une requête http et en fonction si l'endpoint est atteint ou tu met un marqueur rouge ou vers à coter du lien.
Et pour des question de performance optimiser cela de sorte que le test ne se fasse que pour les élément visible dans le viewheight (VH)

**Comment by Aelweak** [comment]
Salut @gloirekiba 👋,

Merci pour la proposition, je la note dans un coin 👍.

Pour le moment, je me contente gentiment d'alimenter la page avec de nouvelles ressources ou des "anciens favoris", que je n'ai pas encore mis, mais j'avais également une liste de petites fonctionnalités "pratiques" à intégrer/pour faciliter "l'utilisation" de la page.

Pour en revenir à ton idée, ce sera certainement "en parallèle" (= "de mon côté"), pour vérifier que les liens fonctionnent (et pour remplacer l'utilisation d'outils de vérif' de liens morts).

Là, de suite, je ne pense pas souhaiter "d'indicateurs visuels", qui, serait "de trop", à mon sens (partant du principe où, si les liens sont dans la liste, c'est qu'ils sont sensés fonctionner 🙂).
