### ISSUE TITLE
Clippy

### ISSUE THREAD

**Issue by Vavart** [Aelweak/liens-utiles#8]
URL : https://bennettfeely.com/clippy/
Section ciblée : CSS > Divers
Description/Commentaire :
Site utile pour faire un clip-path sur-mesure !

**Comment by Aelweak** [comment]
Merci pour la proposition @Vavart 🙏.

Pour tous ces "petits outils", j'avoue les utiliser de temps à autre, depuis Google (ici, en tapant _"clip path generator"_, par exemple) et, pour le coup, il existe des sites déjà bien complets qui les répertorient : https://10015.io/image-tools, https://tools.webdevpuneet.com/, etc... 🙂.
